import type { Metadata } from "next";
import "@/app/globals.css";
import { Chakra_Petch as FontSans } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

import { cn } from "@/lib/utils";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import SessionProvider from "@/components/session-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}
        >
          {children}

          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
